### PR TITLE
Use commonjs build of acorn

### LINKED ISSUE #159: "export 'default' (imported as 'require$$0') was not found in 'acorn'
I recently updated to the latest buble through react-live and my editor stopped working with the following error:

```
"export 'default' (imported as 'require$$0') was not found in 'acorn'
```

It seems that we are trying to use the default import from `acorn` that is gone.

Later I get:

```
TypeError: Cannot read property 'tokTypes' of undefined
```

After inspecting, I realized that it is trying to read `tokTypes` from `acorn`.

### PR DESCRIPTION
**Pull request by adrianheine**
This could fix #159. (See also #160, #161)

### CODE REVIEW

**Comment by alansouzati** [comment]
This is failing with the same issue.

```
Uncaught TypeError: Cannot read property 'tokTypes' of undefined
```

If I inspect the compiled browser distribution I get:

`import require$$0 from 'acorn';`

It does not seem that `module: false` is being used.

**Comment by nathancahill** [comment]
You want to be looking at the other PR @alansouzati. #161.

**Comment by alansouzati** [comment]
I did @nathancahill it fails for me too. i put the comment there with the log

**Comment by adrianheine** [comment]
I tried this with webpack and it doesn't fix #159.

**Comment by adrianheine** [comment]
I tried this with webpack and it doesn't fix #159.

**Comment by adrianheine** [comment]
I tried this with webpack and it doesn't fix #159.

**Comment by adrianheine** [comment]
I tried this with webpack and it doesn't fix #159.

**Comment by adrianheine** [comment]
This doesn't fix #159 with webpack.

**Comment by adrianheine** [comment]
I tried this with webpack and it doesn't fix #159.

**Pull request closed without merging**
