### PR TITLE
Removed acorn as a rollup external to avoid issues with conflicting v…

### PR DESCRIPTION
**Pull request by alansouzati**
…ersions.

Fixes https://github.com/Rich-Harris/buble/issues/159

### CODE REVIEW

**Comment by onigoetz** [comment]
Does this change mean that `acorn` will be bundled with buble directly ?

**Comment by adrianheine** [comment]
That's what it means, and I don't like it and I don't understand why npm does not do this one thing it's supposed to do. @alansouzati Which npm version do you use?

**Comment by onigoetz** [comment]
The question isn't adressed to me, but I use Yarn (1.7.0) and have the same issue

**Comment by alansouzati** [comment]
I’m using the latest NPM and yarn, and both yield the same issue

**Comment by adrianheine** [comment]
I'm closing this in favor of #161 and #162.

**Pull request closed without merging**
