### PR TITLE
Bump magic-string

### LINKED ISSUE #183: Bump magic-string version
I'm keen to land upstream improvements in magic-string introduced in v0.25.2, namely handling of non-latin characters (see https://github.com/Rich-Harris/magic-string/issues/154).

### PR DESCRIPTION
**Pull request by curran**
Closes #183

### CODE REVIEW

**Comment by curran** [comment]
Oh no! CI is failing, but only for Node 4 and 6.

These are the failing tests:

```
    modules.js
      ✓ disallows import statement
      1) disallows export statement
      ✓ imports are ignored with `transforms.moduleImport === false`
      2) exports are ignored with `transforms.moduleExport === false`
      3) imports and exports are ignored with `transforms.modules === false`
      ✓ Supports anonymous functions as default export
      ✓ Supports anonymous classes as default export
```

**Comment by adrianheine** [comment]
That's actually a change in acorn.

**Comment by curran** [comment]
Aha! Excellent insight! Thank you @adrianheine .

**Comment by adrianheine** [comment]
I just pushed 77ab2365788f7d2f0f05f79e2925e98b259404e0 to fix that.

**Comment by curran** [comment]
Closing in favor of https://github.com/Rich-Harris/buble/pull/185

**Comment by adrianheine** [comment]
I think this one could be merged much quicker than #185, see my comments there.

**Comment by curran** [comment]
@adrianheine Makes sense. I merged latest master, should be good to go.

**Comment by adrianheine** [comment]
Most of your changes to `package-lock.json` come from us using different npm or node versions, I guess. If I pull your branch and run `npm i` they are all reverted.

**Comment by curran** [comment]
Yes, I was a bit confused about those changes myself. I apologize if they cause problems.

These are the Node and NPM versions I'm on:

```
$ node --version
v11.9.0
$ npm --version
6.5.0
```

Perhaps best to use your generated version of package-lock, with fewer changes?

**Comment by adrianheine** [comment]
```
$ node --version
v10.15.1
$ npm --version
5.8.0
```
Yeah, keeping my version would be nice since I'm currently the person doing most of the commits in this project. Ideally a `package-lock.json` would not be so volatile, but well …

**Comment by curran** [comment]
Closing in favor of https://github.com/Rich-Harris/buble/pull/186

**Comment by adrianheine** [comment]
btw, I'm absolutely willing to invest some work [squashing](https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/) otherwise good commits, and you could have used [`git add -p`](https://git-scm.com/book/en/v2/Git-Tools-Interactive-Staging) for picking only the parts of your changes we want to merge.

**Comment by curran** [comment]
Ah, good to know for future work. Thanks for the tips!

**Pull request closed without merging**
